### ISSUE TITLE
MacOS cannot create file

### ISSUE THREAD

**Issue by soryeigeton** [sayanarijit/xplr#559]
hi @sayanarijit , i got an error while trying to create file on MacOS Ventura 13.0.1, in the logs in getting 
```
ERROR   process exited with code exit status: 1
```
is this a known issue? or what did i do wrong? the command i run `: c f test.txt`

thanks!

**Comment by sayanarijit** [comment]
Thanks for reporting. Unfortunately I currectly don't have my mac with me, so I'll need your help debugging it.

xplr runs [these commands](https://github.com/sayanarijit/xplr/blob/078da205cadd8e19ed9c1b3323df47f6509adc9b/src/init.lua#L1557) for creating files. So you can try replicating the same by launching shell (i e. type `:!`) and run these commands one by one.

**Comment by soryeigeton** [comment]
<img width="569" alt="Screenshot 2023-01-08 at 22 10 20" src="https://user-images.githubusercontent.com/118413317/211203938-35831f42-4932-4190-a221-49273f8a4659.png">
Hi thanks for the reply, i'm not really sure what to debug here, what i did is i try to run the bash command (although im not familiar with it as well) i attached a screenshot, seems like when creating a file, there's a mkdir command, mkdir is for creating a directory right? the touch command part is working fine.

is there anything i can help from my end?

**Comment by sayanarijit** [comment]
Found it... It seems more command behave differently in linux and mac than I thought. The fix would be

```bash
              if [ "$PTH" ]; then
                DIR="$(dirname $(realpath $PTH))"
                [ "$DIR" ] && mkdir -p -- "$DIR"
                touch -- "$PTH" \
                && "$XPLR" -m 'SetInputBuffer: ""' \
                && "$XPLR" -m 'LogSuccess: %q' "$PTH_ESC created" \
                && "$XPLR" -m 'ExplorePwd' \
                && "$XPLR" -m 'FocusPath: %q' "$PTH"
              else
                "$XPLR" -m PopMode
              fi
```

**Comment by sayanarijit** [comment]
I'll find a mac soon and test it soon. You can also test it and create a pr if you want. Meanwhile could you post the bash version?

bash --version

**Comment by sayanarijit** [comment]
Even better solution: `realpath -m`

**Comment by soryeigeton** [comment]
hi, sorry for the late reply.

my mac is currently running on zsh
zsh version: zsh 5.8.1 (x86_64-apple-darwin22.0)

can you help me understand what is the issue here? cause im still a bit confused, realpath with parameter file, if the file is not created yet it will always output an error from my end

**Comment by sayanarijit** [comment]
Can you pls confirm if [this](https://github.com/sayanarijit/xplr/pull/560/files#diff-a9a99be0ba45d4d8da3becc16047e212b8c236764107727fd08da4a8b7751d5cL1556) works?

**Comment by soryeigeton** [comment]
<img width="365" alt="Screenshot 2023-01-09 at 21 56 13" src="https://user-images.githubusercontent.com/118413317/211337713-1f03292a-1aaf-44af-ad05-4a6a72088988.png">
when i try to run the realpath command with -m options is giving this error

bash version 
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin22)

**Comment by soryeigeton** [comment]
btw thank you for the explanation on the argument etc.sorry if i questioned a lot, but i was wondering, if the objective is to get the current directory, can we use something like `pwd` in bash? and if the purpose is to create a file why is it required to do `mkdir`?

**Comment by sayanarijit** [comment]
> when i try to run the realpath command with -m options is giving this error.

This is problematic. Need to find an alternative.

> GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin22)

This is way too old. The latest release is 5.2. So, I suspect upgrading your Mac's gnu tools should fix this.

https://apple.stackexchange.com/questions/69223/how-to-replace-mac-os-x-utilities-with-gnu-core-utilities

Though mac shouldn't be running such old releases anyway.

> if the objective is to get the current directory

The objective is to get the directory of the entered text.

test.txt -> /curr/dir/test.txt
foo/bar/test.txt -> /curr/dir/foo/bar
../foo/test.txt -> /curr/foo

**Comment by soryeigeton** [comment]
<img width="545" alt="Screenshot 2023-01-10 at 08 50 00" src="https://user-images.githubusercontent.com/118413317/211443576-01dd3de6-73a4-4e80-84a8-c59aebcfb90e.png">
tried with the latest bash version, still getting the same issue. in the `man realpath` i didn't see the -m argument, where did you get that?

**Comment by sayanarijit** [comment]
One possibility is that you only upgraded bash, and [not coreutils](https://apple.stackexchange.com/questions/69223/how-to-replace-mac-os-x-utilities-with-gnu-core-utilities). Bash, realpath etc are path of a collection called gnu coreutils.

**Comment by sayanarijit** [comment]
I have confirmed, if you install coreutils, the updated realpath with -m works fine in macos. I'll update the macos installation docs.

**Comment by soryeigeton** [comment]
Hi @sayanarijit sorry for the late reply, was busy on final exam. sure" thanks!
